### ISSUE TITLE
Event is not an API Gateway request

### ISSUE THREAD

**Issue by umutc** [stackery/php-lambda-layer#18]
Hello there,

I wanna use this layer to poling SQS mail messages in queue and send them via Simple Mail Service.
But i am getting this 500 error on lamda function when test or trigger sos.

**Response**
```
{
  "statusCode": 500,
  "body": "Event is not an API Gateway request"
}
```
**Template**
```
AWSTemplateFormatVersion: 2010-09-09
Description: Magistum Serverless
Transform: AWS::Serverless-2016-10-31
Resources:
  MailPoller:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-mail-poller
      Description: This function reads the SQS mail queue and send them via AWS Simple Mail Service.
      CodeUri: src/php
      Runtime: provided
      Handler: index.php
      MemorySize: 512
      Timeout: 900
      Tracing: Active
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:887080169480:layer:php71:5
      Policies:
        - SQSPollerPolicy:
            QueueName: Magistum-mail-queue
      Environment:
        Variables:
          queueUrl: https://sqs.eu-central-1.amazonaws.com/303814004728/Magistum-mail-queue
```
**Code PHP**
```
require 'vendor/autoload.php';

use Aws\Sqs\SqsClient;
use Aws\Exception\AwsException;

$queueName = "Magistum-mail-queue";

$client = new SqsClient([
    'profile' => 'default',
    'region' => 'eu-central-1',
    'version' => '2012-11-05'
]);

try {
    $result = $client->createQueue(array(
        'QueueName' => $queueName,
        'Attributes' => array(
            'ReceiveMessageWaitTimeSeconds' => 20
        ),
    ));
    var_dump($result);
} catch (AwsException $e) {
    // output error message if fails
    error_log($e->getMessage());
}
```

Thanks...
